name: Trigger auto deployment for vided-spring-boot-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vided-spring-boot-app-AutoDeployTrigger-17c16473-87cd-4040-8471-a1d6d41d6134.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VIDEDSPRINGBOOTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VIDEDSPRINGBOOTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VIDEDSPRINGBOOTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.VIDEDSPRINGBOOTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VIDEDSPRINGBOOTAPP_REGISTRY_PASSWORD }}
          containerAppName: vided-spring-boot-app
          resourceGroup: vided
          imageToBuild: pratikbhosale1188@gmail.com/vided-spring-boot-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


